### ISSUE TITLE
error in admin box class

### ISSUE THREAD

**Issue by raiwa** [BrockleyJohn/Responsive-osCommerce#4]
Hello John,

I tried your modified admin/includes/classes/box.php file under PHP7 and still get this error:
Fatal error: Uncaught Error: Call to undefined method box::tableBlock() in C:\xampp_php_7_0\htdocs\2.3.4BS_Master_2016_04\admin\includes\classes\box.php:26 Stack trace: #0 C:\xampp_php_7_0\htdocs\2.3.4BS_Master_2016_04\admin\modules_content.php(380): box->infoBox(Array, Array) #1 {main} thrown in C:\xampp_php_7_0\htdocs\2.3.4BS_Master_2016_04\admin\includes\classes\box.php on line 26

Do you have any idea what is wrong.

Thanks a lot
Rainer

**Comment by raiwa** [comment]
Hello John,

Found now that if I use your complete set of admin files the mentioned error disappears, but it's because you have a unchanged \admin\includes\classes\table_block.php file which still uses
the same function name like the class name. When I change it to:
__construct
it produces the mention error in the box class.
OK, can do some testing at least, but the final fix for this is not available still??

Thank you for your job with this update.

Regards
Rainer

**Comment by BrockleyJohn** [comment]
Sorry Rainer the file classes/table_block.php is deliberately left unchanged.

This is because the class tableBlock is never instantiated directly in core code and so doesn't need a constructor. 

I have not changed anything that could not be tested by executing core code. If you have a look through the pull request you'll see that in some cases the general strategy of renaming the class name constructor could not be followed and this is one of them.

If there is some reason that this class needs a constructor it should take the form of a separate __construct function that calls the existing class name function, but without a reason I didn't change it.

cheers, John

**Comment by raiwa** [comment]
Hello John,

Thank you. Yes,  I can do testing, I just get deprecated error if I go to Admin => Modules:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; tableBlock has a deprecated constructor in C:\xampp_php_7_0\htdocs\2.3.4BS_Master_2016_04\admin\includes\classes\table_block.php on line 13

Rgds

Rainer

De: John Ferguson [mailto:notifications@github.com] 
Enviado el: sábado, 9 de abril de 2016 18:49
Para: BrockleyJohn/Responsive-osCommerce
CC: Rainer Schmied
Asunto: Re: [BrockleyJohn/Responsive-osCommerce] error in admin box class (#4)

Sorry Rainer the file classes/table_block.php is deliberately left unchanged.

This is because the class tableBlock is never instantiated directly in core code and so doesn't need a constructor. 

I have not changed anything that could not be tested by executing core code. If you have a look through the pull request you'll see that in some cases the general strategy of renaming the class name constructor could not be followed and this is one of them.

If there is some reason that this class needs a constructor it should take the form of a separate __construct function that calls the existing class name function, but without a reason I didn't change it.

cheers, John

**Comment by BrockleyJohn** [comment]
fix pushed

**Comment by BrockleyJohn** [comment]
Thanks for testing, Rainer. I don’t know how things got out of step but my test environment contains a fix for this that wasn’t in the branch.

It’s committed and pushed now to my branch

Cheers

John

**Comment by raiwa** [comment]
John,

That's ok now. Meanwhile the dashboard modules need to be updated too.

Thank You and best regards
Rainer

**Comment by raiwa** [comment]
Sorry to bother you, do you plan to update the store side to PHP 7 compatibility?

**Comment by BrockleyJohn** [comment]
There are plans to update everything, this is just the first step. See
[https://github.com/gburton/Responsive-osCommerce/issues/288](url)
