### ISSUE TITLE
https://github.com/BrockleyJohn/Responsive-osCommerce/tree/php7_compatibility_01

### ISSUE THREAD

**Issue by boelle** [BrockleyJohn/Responsive-osCommerce#5]
are there any way to be autoamtic notified when updates happen?

**Comment by BrockleyJohn** [comment]
I'll update this issue if you like. I don't see the point though - when you've taken them they are already in your project branch. Any merge conflicts that arise for my branch will also arise merging the new master into your project.

**Comment by boelle** [comment]
it's more that i run this in a real store, and its solid.

Its so solid that i don't think of it, and as i have just found out the files on the webserver is now a bit out of date.

the way i update is by pulling everything from the webserver to one folder and then in another folder i have everything from https://github.com/BrockleyJohn/Responsive-osCommerce/tree/php7_compatibility_01

i then use kdiff3 to compare everything on a file by file basis and where there are changes i edit the ones from the webserver

i do it in this way as a few files are modded by the payment gateway modules

it maybe a bit stupid way but if i get an email of some kind when new stuff happens i can update the same way with a smaller list of files to edit
